name: stocksip
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0    
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.2
  path: ^1.9.1
  lottie: ^3.3.2
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/stocksip_icon.jpg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/stocksip_logo.png
    - assets/lottie/stocksip_splash.json
